import { Inter } from "next/font/google";
import "./globals.css";
import Toploader from "@/components/sub-components/TopLoader";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-semiDark pb-8`}>
        <Toploader />
        {children}
      </body>
    </html>
  );
}
