import AdminSidebar from "@/components/sub-components/AdminSidebar";
import "./../globals.css";
import SideNavbar from "@/components/sub-components/SideNavbar";

export const metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (
    <>
      <AdminSidebar />
      <div className="admin-contents">{children}</div>
    </>
  );
}
